apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hivebox
  name: hivebox-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "true"
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: hivebox
