apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hive-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hivebox-service
            port:
              number: 8000

  - http:
      paths:
      - path: /metricsui
        pathType: Prefix
        backend:
          service:
            name: prometheus-service.monitoring
            port:
              number: 8080
