apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hivebox
  name: hivebox-service
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: hivebox
  type: NodePort
status:
  loadBalancer: {}
