apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2025-03-13T14:00:44Z"
  generation: 1
  labels:
    app: hivebox
  name: hivebox
  namespace: default
  resourceVersion: "53037"
  uid: 0d9311c8-04c9-4cad-8de6-b4136f0f4077
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hivebox
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hivebox
    spec:
      containers:
      - image: ghcr.io/sabryp3/hivebox:latest
        imagePullPolicy: Always
        name: hivebox
        ports:
        - containerPort: 8000
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
        - name: github-sec
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
