apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoic2FicnlwMyIsInBhc3N3b3JkIjoiZ2hwX2w4ZjR1a3dUR095b0RPRGhlbTFOcEZCUnpmYnhqVzEyekVJRyIsImF1dGgiOiJjMkZpY25sd016cG5hSEJmYkRobU5IVnJkMVJIVDNsdlJFOUVhR1Z0TVU1d1JrSlNlbVppZUdwWE1USjZSVWxIIn19fQ==
kind: Secret
metadata:
  creationTimestamp: "2025-03-13T13:54:16Z"
  name: github-sec
  namespace: default
  resourceVersion: "52480"
  uid: 874234d8-6e04-40b0-aac0-2b7a245943f1
type: kubernetes.io/dockerconfigjson
