apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: valkey-svc
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: valkey-cache
  type: ClusterIP
status:
  loadBalancer: {}
