
name: Terrascan flow
on:
  push:
  workflow_dispatch:

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'k8s'
        iac_version: 'v1'
        policy_type: 'k8s'
        only_warn: true
        sarif_upload: true-action/init@v3
      with:
        languages: python
        iac_dir: 'k8s/'
        #non_recursive:
        #policy_path:
        #skip_rules:
        #config_path:
        #webhook_url:
        #webhook_token:
        
    - name: Upload

    - name: Perform CodeQL Analysis
      uses: github SARIF file
      uses: github/codeql-action/upload/codeql-action/analyze@v3     
